[package]
name = "oslog"
description = "A minimal safe wrapper around Apple's unified logging system"
repository = "https://github.com/steven-joruk/oslog"
version = "0.0.5-alpha.0"
authors = ["Steven Joruk <steven@joruk.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["log", "logging", "unified", "macos", "apple"]
categories = ["development-tools::debugging"]

[features]

default = ["logger"]

# Enables support for the `log` crate
logger = ["dashmap", "log"]

[dependencies]
log = { version = "0.4", features = ["std"], optional = true }
dashmap = { version = "4", optional = true }

[build-dependencies]
cc = "1.0"
